language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  # Set in the settings page of your repository, as a secure variable
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
